
services:

  admin:
    build: ./images/admin
    image: crshlab/autodidactadmin:latest
    ports:
      - 8081:80
    networks:
      - backend
    volumes:
      -  ./images/admin/src/:/usr/share/nginx/html/
    environment:
      API_ENDPOINT:
      
  student:
    build: ./images/student
    image: crshlab/autodidactstudent:latest
    ports:
      - 8080:80
    networks:
      - backend
    volumes:
      -  ./images/student/src/:/usr/share/nginx/html/
    environment:
      API_ENDPOINT: 
      
  api:
    build: ./images/api
    image: crshlab/autodidactapi:latest
    container_name: "api"
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER:
      POSTGRES_DATABASE: "postgres"
      POSTGRES_PASSWORD:
      POSTGRES_HOST: db
    volumes:
      - ./images/api/src:/usr/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend  


  db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_DATABASE:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD:
    volumes:
      - ./images/_volumes/pg:/var/lib/postgresql/
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5


  # facerec_service:
  #   build: ./images/face_recognition
  #   ports:
  #     - 8081:8080
  #   volumes:
  #     - ./images/face_recognition/faces:/root/faces
  #   restart: always

  # libretranslate:
  #   container_name: libretranslate
  #   image: libretranslate/libretranslate:latest
  #   ports:
  #     - "5001:5000"
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ['CMD-SHELL', './images/venv/bin/python scripts/healthcheck.py']
  #     interval: 10s
  #     timeout: 4s
  #     retries: 4
  #     start_period: 5s
  #   environment:
  #     - LT_LOAD_ONLY=en,nl
  #   volumes:
  #     - ./images/libretranslate:/home/libretranslate/.local:rw
  #   networks:
  #     - backend


  ollama: 
    image: ollama/ollama:latest
    ports: 
      - 11434:11434
    volumes: 
      - ./images/ollama:/root/.ollama
    networks:
      - backend

networks:
  backend:
    # Specify driver options
    driver: bridge