
services:

  admin:
    image: crshlab/autodidactadmin:latest
    ports:
      - 8081:80
    networks:
      - backend

  student:
    image: crshlab/autodidactstudent:latest
    ports:
      - 8080:80
    networks:
      - backend
      
  api:
    image: crshlab/autodidactapi:latest
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER:
      POSTGRES_DATABASE: "postgres"
      POSTGRES_PASSWORD:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend


  db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_DATABASE:
      POSTGRES_DB: POSTGRES_DATABASE
      POSTGRES_PASSWORD:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./_volumes/pg:/var/lib/postgresql/
    networks:
      - backend

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # facerec_service:
  #   build: ./face_recognition
  #   ports:
  #     - 8081:8080
  #   volumes:
  #     - ./face_recognition/faces:/root/faces
  #   restart: always

  # libretranslate:
  #   container_name: libretranslate
  #   image: libretranslate/libretranslate:latest
  #   ports:
  #     - "5001:5000"
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
  #     interval: 10s
  #     timeout: 4s
  #     retries: 4
  #     start_period: 5s
  #   environment:
  #     - LT_LOAD_ONLY=en,nl
  #   volumes:
  #     - ./libretranslate:/home/libretranslate/.local:rw
  #   networks:
  #     - backend


  # ollama: 
  #   image: ollama/ollama:latest
  #   ports: 
  #     - 11434:11434
  #   volumes: 
  #     - ./ollama:/root/.ollama
  #   networks:
  #     - backend

networks:
  backend:
    # Specify driver options
    driver: bridge
